language: python

arch:
    - arm64
env:
  - PIP_NO_CACHE_DIR=off
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t raspberrypi-telegram-bot .
      - docker images
      - docker tag raspberrypi-telegram-bot $DOCKER_USERNAME/raspberrypi-telegram-bot
      - docker push $DOCKER_USERNAME/raspberrypi-telegram-bot